name: Chocolatine Workflow

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
env:
  MIRROR_URL: "git@github.com:Epitech-Mirror-Repo.git"
  EXECUTABLES: "mysh"

jobs:
  check_coding_style:
    name: Check Coding Style
    runs-on: ubuntu-latest
    if: "!startsWith(github.ref_name, 'ga-ignore-') && github.repository != env.MIRROR_URL"
    container: ghcr.io/epitech/coding-style-checker:latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Coding Style Checker
        run: check.sh $(pwd) $(pwd)

      - name: Display Errors
        run: |
          if [ -f coding-style-reports.log ]; then
            while IFS= read -r line; do
              echo "::error file=${line%%:},line=${line##:}::Coding style issue"
            done < coding-style-reports.log
            exit 1
          fi

  check_program_compilation:
    name: Check Compilation
    runs-on: ubuntu-latest
    needs: check_coding_style
    container: epitechcontent/epitest-docker
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Compile Project
        run: |
          timeout 120 make || { echo "::error::Compilation failed"; exit 1; }

      - name: Clean Compilation
        run: make clean

      - name: Check Executables
        run: |
          for exec in $(echo "$EXECUTABLES" | tr ',' ' '); do
            if [ ! -x "$exec" ]; then
              echo "::error file=$exec::Executable not found or not executable"
              exit 1
            fi
          done

  run_tests:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: check_program_compilation
    container: epitechcontent/epitest-docker
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Tests
        run: timeout 120 make tests_run || { echo "::error::Tests failed"; exit 1; }

  push_to_mirror:
    name: Push to Mirror
    runs-on: ubuntu-latest
    needs: run_tests
    if: github.event_name == 'push'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GIT_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $(echo $MIRROR_URL | awk -F/ '{print $3}') >> ~/.ssh/known_hosts

      - name: Mirror Repository
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{ env.MIRROR_URL }}
          ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}